apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactive-eventservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactive-eventservice
  template:
    metadata:
      labels:
        app: reactive-eventservice
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: reactive-eventservice
        image: cptdockerregistry.azurecr.io/event-service:latest
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: reactive-eventservice
spec:
  ports:
  - port: 6379
  selector:
    app: reactive-eventservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactive-eventservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactive-eventservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: reactive-eventservice
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: reactive-eventservice
        image: cptdockerregistry.azurecr.io/event-service:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "reactive-eventservice"
---
apiVersion: v1
kind: Service
metadata:
  name: reactive-eventservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: reactive-eventservice
